networks:
  sprint-network:
    driver: bridge

volumes:
  mongo-data:

services:
  mongodb:
    image: mongo:latest
    container_name: sprint-mongodb
    ports:
      - "27017:27017"
    networks:
      - sprint-network
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: sprint-backend
    ports:
      - "8080:8080"
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - sprint-network

  frontend:
    build: ./frontend
    container_name: sprint-frontend
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - sprint-network
