name: Deploy to GCP

on:
  push:
    branches:
      - Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            set -e

            cd /home/pawel_kelar_put/TSD

            git config --global --add safe.directory /home/pawel_kelar_put/TSD

            
            sudo chown -R $USER:$USER /home/pawel_kelar_put/TSD
            sudo chmod -R u+rwX /home/pawel_kelar_put/TSD

            git fetch origin
            git reset --hard origin/main

            cat <<EOF | sudo tee .env > /dev/null
            JWT_SECRET=${{ secrets.JWT_SECRET }}
            JWT_EXPIRATION_MS=${{ secrets.JWT_EXPIRATION_MS }}
            EOF

            sudo docker-compose up -d --build --force-recreate

            sudo docker image prune -f
