name: Deploy to GCP

on:
  push:
    branches:
      - Deploy

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.GCP_VM_IP }}
          username: ${{ secrets.GCP_USERNAME }}
          key: ${{ secrets.GCP_SSH_PRIVATE_KEY }}
          command_timeout: 60m
          script: |
            cd /home/pawel_kelar_put/TSD
            
            # Pobranie najnowszego kodu
            git pull origin main
            
            sudo docker-compose up -d --build
            
            sudo docker image prune -f
